# Generated by oxcel's release workflow (.github/scripts/cask.sh); don't edit by hand.
cask "oxcel" do
  version "0.4.4"
  sha256 "a3cd85a80962c712d40b94c827464c453498eb05021abb308e0661c24147ed55"

  url "https://github.com/akhil-gautam/homebrew-oxcel/releases/download/v#{version}/oxcel-#{version}-macos-universal.zip"
  name "oxcel"
  desc "Spreadsheet for files with billions of rows"
  homepage "https://github.com/akhil-gautam/homebrew-oxcel"

  app "oxcel.app"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/oxcel.app"]
  end

  # Not ~/Library/Caches/oxcel or ~/Library/Application Support/oxcel: they
  # hold the user's edits, pivots, settings and license.
  zap trash: [
    "~/Library/Caches/dev.oxcel.app",
    "~/Library/Logs/oxcel",
    "~/Library/Saved Application State/dev.oxcel.app.savedState",
    "~/Library/WebKit/dev.oxcel.app",
  ]
end
